analyzer:
  exclude:
    - lib/**/translations.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

  errors:
    always_specify_types: error
    always_declare_return_types: error
    camel_case_types: error
    always_put_control_body_on_new_line: error
    always_put_required_named_parameters_first: error
    annotate_overrides: error
    avoid_empty_else: error
    avoid_print: error
    avoid_types_as_parameter_names: error
    avoid_unused_constructor_parameters: error
    avoid_unnecessary_containers: error
    await_only_futures: error
    cancel_subscriptions: error
    close_sinks: error
    constant_identifier_names: error
    control_flow_in_finally: error
    directives_ordering: error
    empty_constructor_bodies: error
    empty_statements: error
    iterable_contains_unrelated_type: error
    file_names: error
    hash_and_equals: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    prefer_adjacent_string_concatenation: error
    prefer_conditional_assignment: error
    prefer_contains: error
    prefer_is_empty: error
    prefer_is_not_empty: error
    prefer_final_fields: error
    prefer_single_quotes: error
    prefer_spread_collections: error
    recursive_getters: error
    valid_regexps: error
    unnecessary_brace_in_string_interps: error
    unnecessary_const: error
    unnecessary_new: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_this: error
    unused_import: error
    use_rethrow_when_possible: error


linter:
  rules:
    - always_declare_return_types
    - always_specify_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_empty_else
    - avoid_print
    - avoid_types_as_parameter_names
    - avoid_unused_constructor_parameters
    - avoid_unnecessary_containers
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - constant_identifier_names
    - control_flow_in_finally
    - directives_ordering
    - empty_constructor_bodies
    - empty_statements
    - iterable_contains_unrelated_type
    - file_names
    - hash_and_equals
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_adjacent_string_concatenation
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_final_fields
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - valid_regexps
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - use_rethrow_when_possible